export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getCurrentUser } from "@/actions/getCurrentUser";
import SignInModal from "@/components/modals/SignInModal";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import AddressModal from "@/components/modals/AddressModal";
import SignUpModal from "@/components/modals/SignUpModal";

const catamaran = Catamaran({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${catamaran.className} antialiased bg-white max-w-[1590px] overflow-x-hidden mx-auto`}
      >
        <Toaster/>
        <Navbar currentUser={currentUser} />
        <SignInModal />
        <SignUpModal />
        <AddressModal />
        <div className="min-h-[70vh]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
